#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_Register_hello:
    path: /Register/hello
    controller: App\Controller\RegisterController::hello
    
app_edit_cuenta:
    path: /EditarCuentaController/edit
    controller: App\Controller\EditarCuentaController::edit

app_Provincia_findProvinciasByPais:
    path: /ProvinciasController/findProvinciasByPais
    controller: App\Controller\ProvinciasController::findProvinciasByPais